# This is a config for E2B sandbox template.
# You can use template ID (ogdc9n6xsssij4ylknsz) or template name (cc-nextjs-developer1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("cc-nextjs-developer1") # Sync sandbox
# sandbox = await AsyncSandbox.create("cc-nextjs-developer1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cc-nextjs-developer1')

team_id = "e66eebb1-da21-4fc5-8692-677e2b38ab70"
dockerfile = "e2b.Dockerfile"
template_name = "cc-nextjs-developer1"
template_id = "ogdc9n6xsssij4ylknsz"
